version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
      - MYSQL_USER=${{ secrets.MYSQL_USER }}
      - MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
      - CI_ENV=true
    networks:
      - app-network
    depends_on:
      - db

  client_web:
    build:
      context: .
      dockerfile: client_web/Dockerfile
    environment:
      - CI_ENV=true
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - server

  client_mobile:
    build:
      context: .
      dockerfile: client_mobile/Dockerfile
    environment:
      - CI_ENV=true
    networks:
      - app-network
    depends_on:
      - server

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./SQL/Database_create:/docker-entrypoint-initdb.d

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
