services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db

  client_web:
    build:
      context: .  # Root directory to access client/area
      dockerfile: client_web/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - server

  client_mobile:
    build:
      context: .  # Root directory to access client/area
      dockerfile: client_mobile/Dockerfile
    networks:
      - app-network
    depends_on:
      - server

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge