services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - apk-volume:/usr/src/app/shared
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  client_web:
    build:
      context: .  # Root directory to access client/area
      dockerfile: client_web/Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - server

  client_mobile:
    build:
      context: .  # Root directory to access client/area
      dockerfile: client_mobile/Dockerfile
    networks:
      - app-network
    volumes:
      - apk-volume:/usr/src/app/shared
    depends_on:
      - server

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./SQL/Database_create:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
  apk-volume:

networks:
  app-network:
    driver: bridge
