name: Integration Continue

on:
  push:
    branches:
      - main
env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-DEV-500-MPL-5-1-area-ewan.massonet.git"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build server image
        run: |
          docker build -t my-server-image:latest -f server/Dockerfile server

      - name: Build client_web image
        run: |
          docker build -t my-client-web-image:latest -f client_web/Dockerfile .

      - name: Build client_app image
        run: |
          docker build -t my-client-app-image:latest -f client_mobile/Dockerfile .

      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
