name: Integration Continue

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup environment variables
        run: |
          echo "CI_ENV=true" >> $GITHUB_ENV

      - name: Build server image
        run: |
          docker build -t my-server-image:latest -f server/DockerfileTest server

      - name: Build client_app image
        run: |
          docker build -t my-client-app-image:latest -f client_mobile/Dockerfile .

      - name: Build client_web image
        run: |
          docker build -t my-client-web-image:latest -f client_web/Dockerfile .

      - name: Run docker compose
        run: |
          docker-composeup
  
      - name: Wait for MySQL to be ready
        run: |
            until mysqladmin ping -h db -u user -ppass --silent; do
              echo "Waiting for MySQL to be ready..."
              sleep 5
            done 

      - name: Wait for server to be ready
        run: |
          until curl -s http://localhost:8080/health; do
            echo "Waiting for server to be ready..."
            sleep 5
          done

      - name: Run tests on the server
        run: |
          docker exec my-server-container npm test

      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
