name: Integration Continue

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build server image
        run: |
          docker build -t my-server-image:latest -f server/Dockerfile server

      - name: Build client_web image
        run: |
          docker build -t my-client-web-image:latest -f client_web/Dockerfile .

      - name: Build client_app image
        run: |
          docker build -t my-client-app-image:latest -f client_mobile/Dockerfile .

      - name: Configure SSH for GitHub
        if: success()
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        if: success()
        run: |
          git config --global user.email "amir.madaoui@epitech.eu"
          git config --global user.name "amir madaoui"

      - name: Push to Mirror Repo
        if: success()
        run: |
          git remote add mirror git@github.com:EpitechPromo2027/B-DEV-500-MPL-5-1-area-ewan.massonet.git
          
          echo "Fetching latest changes from mirror repository..."
          git fetch

          echo "Merging changes from mirror repository..."
          git merge main --strategy-option theirs

          echo "Pushing to mirror repository..."
          git push HEAD:main