name: Integration Continue

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        volumes:
          - mysql-data:/var/lib/mysql
          - ./SQL:/docker-entrypoint-initdb.d
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 -u user -ppass --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done 

      - name: Setup environment variables
        run: |
          echo "CI_ENV=true" >> $GITHUB_ENV

      - name: Build server image
        run: |
          docker build -t my-server-image:latest -f server/DockerfileTest server

      - name: Run server container
        run: |
          docker run -d --name my-server-container -p 8080:8080 my-server-image:latest

      - name: Wait for server to be ready
        run: |
          until curl -s http://localhost:8080/health; do
            echo "Waiting for server to be ready..."
            sleep 5
          done

      - name: Run tests on the server
        run: |
          docker exec my-server-container npm test

      - name: Build client_web image
        run: |
          docker build -t my-client-web-image:latest -f client_web/Dockerfile .

      - name: Stop and remove server container
        run: |
          docker stop my-server-container
          docker rm my-server-container

      - name: Build client_app image
        run: |
          docker build -t my-client-app-image:latest -f client_mobile/Dockerfile .

      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
