name: Integration Continue

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .env file
        run: |
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

      - name: Afficher les valeurs de l'environnement
        run: cat .env

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run docker compose
        run: |
          docker-compose -f docker-compose-ci.yml up -d

      - name: Wait for MySQL to be ready
        run: |
            until mysqladmin ping -h 127.0.0.1 -u user -ppass --silent; do
              echo "Waiting for MySQL to be ready..."
              sleep 5
            done 

      - name: Wait for server to be ready
        run: |
          until curl -s http://localhost:8080/health; do
            echo "Waiting for server to be ready..."
            sleep 5
          done

      - name: log db statue
        run: |
          docker-compose -f docker-compose-ci.yml logs db

      - name: Run tests on the server
        run: |
            docker-compose -f docker-compose-ci.yml exec -T server npm test
  
      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
